### PR TITLE
adding android sms, call import + some docs

### PR DESCRIPTION
**Pull request by delijati**
Android import sms, call history + README

### CODE REVIEW

**Comment by delijati** [comment]
Maybe this would make more sense to put it into a separate repo or even create `click` + `ui`

**Comment by mariogrip** [comment]
Are you sure this is for bionic and not xenial? is this for desktop?

**Comment by delijati** [comment]
I developed on bionic (my desktop) so thats why i used this branch

**Review by UniversalSuperBox — CHANGES_REQUESTED** [review]
I know it's been quite a while since you opened this... I'm sorry for that. Now that you have more knowledge of the system, could you make these changes on top of `xenial` so they can be merged and used by the phone platform?

**Comment by delijati** [comment]
@UniversalSuperBox created a new branch from `xenial`

**Comment by UniversalSuperBox** [comment]
Replaced by https://github.com/ubports/history-service/pull/8

**Pull request closed without merging**
