### PR TITLE
add MessageStatus Draft

### PR DESCRIPTION
**Pull request by lduboeuf**
Prepare to store message as draft in history db,
refs: https://github.com/ubports/messaging-app/issues/151

### CODE REVIEW

**Comment by mardy** [comment]
This is obviously good, but I'd rather merge it once the feature is at least partially working.

**Comment by lduboeuf** [comment]
@mardy i've pushed a PR in messaging-app that use those flags
Now waiting for this PR to be merged :)

**Comment by UniversalSuperBox** [comment]
@mardy, would you continue blocking this PR for that reason? Would you rather I gave Lionel write access to history-service and messaging-app so he can make a branch extension repository and test both changes at the same time?

**Comment by lduboeuf** [comment]
i don't think having write access only for this small PR is a good idea. But i will be thanksfull if merged ;-), will be easier for testers on messaging-app, no side effects expected according to my tests.

**Comment by mardy** [comment]
Sorry, I didn't intend to block this :-) +1 from me :-)

**Review by mardy — APPROVED** [review]

**Comment by lduboeuf** [comment]
so what is the next step now, someone need to merge it ? or it needs a fake empty commit ?

**Comment by Flohack74** [comment]
Sorry, this was forgotten ;)

**Comment by lduboeuf** [comment]
thx, i can rework now on the draft again :)

**Comment by lduboeuf** [comment]
@Flohack74 humm, i don't see any updates on the last devel image for history-service. I think debian changelog should be updated, no ?

**Pull request merged**
