### PR TITLE
[DO NOT MERGE] add MessageStatus Draft

### PR DESCRIPTION
**Pull request by lduboeuf**
Prepare History Service to store messages as draft

### CODE REVIEW

**Comment by lduboeuf** [comment]
no CI for history-service ?

**Comment by Flohack74** [comment]
Never heard about history-service ;) - Ping me on the evening, I can set up CI for it...

**Comment by lduboeuf** [comment]
humm, so the CI cry for DaemonTest, and not only related to this commit. Seems to be broken

**Comment by Flohack74** [comment]
Then fix it please ;) - we will no longer disable tests because that can create serious issues. In fact, we would need to add much more tests...

**Comment by lduboeuf** [comment]
I think it is more a build setup issue as it doesn't build since 2018.

**Comment by lduboeuf** [comment]
out of my skills sorry :)

**Comment by lduboeuf** [comment]
tests works locally, so don't know where it can be.
The removing of ( <!nocheck> ) of xvfb in control  make the tests pass on amd64 but not in armhf/arm64 .

**Comment by mardy** [comment]
Please don't remove the `<!nocheck>` flag, it should be irrelevant to this case.

How are building the package? Do you use crossbuilder? With the target arch set to amd64?

If yes, then I recommend running the `HistoryGroupedThreadsModelTest` test with valgrind. In CI it appears to crash after having successfully executed all the tests:

```
19: HistoryGroupedThreadsModelTest: ********* Start testing of HistoryGroupedThreadsModelTest *********
19: HistoryGroupedThreadsModelTest: Config: Using QtTest library 5.9.5, Qt 5.9.5 (arm64-little_endian-lp64 shared (dynamic) release build; by GCC 5.4.0 20160609)
19: HistoryGroupedThreadsModelTest: PASS   : HistoryGroupedThreadsModelTest::initTestCase()
19: HistoryGroupedThreadsModelTest: QWARN  : HistoryGroupedThreadsModelTest::testCanFetchMore() Could not find group for property  QVariant(QVariantList, (QVariant(QVariantMap, QMap(("accountId", QVariant(QString, "accountId0"))("alias", QVariant(QString, ""))("avatar", QVariant(QString, ""))("contactId", QVariant(QString, ""))("detailProperties", QVariant(QVariantMap, QMap()))("identifier", QVariant(QString, "textParticipant"))("roles", QVariant(uint, 0))("state", QVariant(uint, 0))))))
19: HistoryGroupedThreadsModelTest: PASS   : HistoryGroupedThreadsModelTest::testCanFetchMore()
19: HistoryGroupedThreadsModelTest: PASS   : HistoryGroupedThreadsModelTest::testThreadsUpdated()
19: HistoryGroupedThreadsModelTest: PASS   : HistoryGroupedThreadsModelTest::cleanupTestCase()
19: HistoryGroupedThreadsModelTest: Totals: 4 passed, 0 failed, 0 skipped, 0 blacklisted, 962ms
19: HistoryGroupedThreadsModelTest: ********* Finished testing of HistoryGroupedThreadsModelTest *********
19: *** Error in `/build/history-service-0.3~0ubports1+0~20200205104357.5~1.gbp88ccc8/obj-aarch64-linux-gnu/tests/Ubuntu.History/HistoryGroupedThreadsModelTest': double free or corruption (out): 0x00000000209c8ac0 ***
19: HistoryGroupedThreadsModelTest: Exited with status 6
```

This might be a real error in the code, so we'd better investigate it. `valgrind` should help, but if you cannot run it and can only use CI for testing, then I'd recommend starting by commenting out the various test functions in this class, and see if you can find out which one is causing the problem.

**Comment by lduboeuf** [comment]
Oh yes sorry, this was for testing, i will edit this PR or remove those commits tomorrow to avoid confusion. 

Ouch it is going to be a long way for me to find out what is wrong with tests. Interesting things is that tests went fine on amd64.

**Comment by lduboeuf** [comment]
I close that PR, as it was no more a "add draft status" and more a "try to fix CI build" but i'm stuck now. Tests works locally with crossbuilder ( but not each time ) and never on CI. I give up as i'm not used to c++ tests and test env.
Note that by removing the "<!nocheck>" in debian/control for "rvfb" makes it build for amd64 but not arm*

**Pull request closed without merging**
